# Generated by Django 5.0.13 on 2025-12-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadolavanderia',
            name='dni',
        ),
    ]
