# Generated by Django 5.0.13 on 2025-12-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_remove_empleadolavanderia_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidolavanderia',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='app_gestion.maquinalavanderia'),
        ),
    ]
