# Generated by Django 5.0.13 on 2025-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0003_detallepedidolavanderia_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidolavanderia',
            name='maquina',
        ),
        migrations.AddField(
            model_name='detallepedidolavanderia',
            name='maquinas',
            field=models.ManyToManyField(related_name='detalles_pedido', to='app_gestion.maquinalavanderia'),
        ),
    ]
