# Generated by Django 5.0.13 on 2025-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0004_remove_detallepedidolavanderia_maquina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteoperacional',
            name='tiempo_inactividad_maquinas',
            field=models.IntegerField(verbose_name='Tiempo de inactividad de mÃ¡quinas (horas)'),
        ),
    ]
