# Generated by Django 5.0.13 on 2025-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0005_alter_reporteoperacional_tiempo_inactividad_maquinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientelavanderia',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='reporteoperacional',
            name='tiempo_inactividad_maquinas',
            field=models.IntegerField(verbose_name='Tiempo de inactividad de máquinas (horas)'),
        ),
    ]
